const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless:true });
  const page = await browser.newPage({ viewport:{width:390,height:844} });
  const errors=[];
  page.on('pageerror', e => errors.push(e.message));
  await page.route('https://**.supabase.co/**', route => {
    const products = [{slug:'heroee8-aio',name_th:'ทดสอบ <img src=x onerror="window.pwned=1">',name_en:'Test',category:'bess',description_th:'รายละเอียด',description_en:'Description',images:['/01.webp'],specs:{Energy:'8 kWh'}}];
    route.fulfill({contentType:'application/json',body:JSON.stringify(route.request().url().includes('/products?') ? products : [])});
  });
  for (const path of ['index.html','products.html','contact.html','quote.html','news.html']) {
    await page.goto('http://localhost:3100/'+path);
    await page.locator('.nav-burger').click();
    assert.equal(await page.locator('.nav-burger').getAttribute('aria-expanded'),'true',path);
    assert.equal(await page.locator('.nav-links').isVisible(),true,path);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.nav-links').isVisible(),false,path);
    await page.locator('#btnEN').click();
    assert.equal(await page.locator('body').getAttribute('data-lang'),'en');
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth+1);
    assert.equal(overflow,false,'Mobile overflow: '+path);
  }
  await page.goto('http://localhost:3100/products.html');
  await page.locator('.prod-card').waitFor();
  assert.equal(await page.evaluate(()=>window.pwned),undefined);
  assert.equal(await page.locator('.prod-body img').count(),0);
  assert.match(await page.locator('.prod-img').getAttribute('href'),/^\/products\//);
  await page.goto('http://localhost:3100/quote.html?product=bess');
  assert.equal(await page.locator('[name=products][value=bess]').isChecked(),true);
  for(const [name,value] of Object.entries({name:'Test User',company:'Example',phone:'0812345678',email:'test@example.com'})) await page.locator(`[name=${name}]`).fill(value);
  await page.locator('[name=business_type]').selectOption({index:1});
  let submitted;
  await page.route('**/api/leads', async route => { submitted=route.request().postDataJSON(); await route.fulfill({status:503,contentType:'application/json',body:'{"error":"unavailable"}'}); });
  await page.locator('[type=submit]').click();
  await page.locator('.form-feedback[data-error=true]').waitFor();
  assert.equal(await page.locator('[name=name]').inputValue(),'Test User');
  assert.equal(await page.locator('#successState').isVisible(),false);
  await page.unroute('**/api/leads');
  await page.route('**/api/leads', async route => { submitted=route.request().postDataJSON(); await route.fulfill({status:201,contentType:'application/json',body:'{"ok":true}'}); });
  await page.locator('[type=submit]').click();
  await page.locator('#successState.show').waitFor();
  assert.equal(submitted.kind,'quote'); assert.deepEqual(submitted.products,['bess']);
  await page.goto('http://localhost:3100/contact.html');
  for(const [name,value] of Object.entries({name:'Test User',phone:'0812345678',email:'test@example.com',message:'Hello'})) await page.locator(`[name=${name}]`).fill(value);
  await page.locator('[type=submit]').click();
  await page.locator('#successMsg.show').waitFor(); assert.equal(submitted.kind,'contact');
  await page.goto('http://localhost:3100/news.html');
  await page.locator('#newsletterForm [name=email]').fill('test@example.com');
  await page.locator('#newsletterForm [type=submit]').click();
  await page.waitForFunction(()=>document.querySelector('#newsletterForm .form-feedback').textContent.includes('received'));
  assert.equal(submitted.kind,'newsletter');
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://localhost:3100/index.html');
  await page.waitForTimeout(400);
  fs.mkdirSync('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/v2-home-desktop.png',fullPage:false});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/v2-home-mobile.png',fullPage:false});
  assert.deepEqual(errors,[]);
  console.log('Browser checks passed: mobile navigation, language persistence, overflow, escaped CMS, quote/contact/newsletter success and failure.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
